import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={spaceGrotesk.style}
        className={cn("min-h-screen font-sans antialiased")}
      >
        <header>
          <strong>react-screen-wake-lock</strong>
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
