name: CI

'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish-module:
    name: 'Publish Module to NPM on Node ${{ matrix.node }} and ${{ matrix.os }}'
    needs: build
    if: github.repository == 'jorisre/react-screen-wake-lock' && (github.ref =='refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: 'Use Node ${{ matrix.node }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn build
      - name: Publish
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: '${{secrets.NPM_TOKEN}}'
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
